service: midas-promotions-blue
runtime: nodejs20
instance_class: F1  # (optional) adjust based on your scaling needs

env_variables:
  NODE_ENV: 'production'

handlers:
  - url: /_next/static
    static_dir: .next/static
    secure: always

  - url: /.*
    script: auto
    secure: always
